In [ ]:
df <- read.csv('/content/dataCow1.csv')
head(df)

  Порядковый.номер Порода      Живая.масса Процент.жирности Способ.кормления
1 1                Ярославская 460.87      3.96             Травяной
2 2                Ярославская 516.90      4.06             Травяной
3 3                Ярославская 574.52      3.71             Травяной
4 4                Ярославская 484.74      3.90             Травяной
5 5                Ярославская 530.79      3.92             Травяной
6 6                Ярославская 538.23      4.03             Травяной
  Годовой.удой.в.кг
1 3266.47
2 3443.58
3 4050.08
4 3387.03
5 3723.41
6 3553.66

In [ ]:
cor(df[,c(3,4,6)])

                  Живая.масса Процент.жирности Годовой.удой.в.кг
Живая.масса        1.0000000  -0.5891939        0.9555421
Процент.жирности  -0.5891939   1.0000000       -0.6650004
Годовой.удой.в.кг  0.9555421  -0.6650004        1.0000000

In [ ]:
df$`Порода` <- as.factor(df$`Порода`)
df$`Способ.кормления` <- as.factor(df$`Способ.кормления`)

In [ ]:
fit <- lm(Годовой.удой.в.кг ~ Процент.жирности, data = df)
summary(fit)

Call:
lm(formula = Годовой.удой.в.кг ~ Процент.жирности,
    data = df)

Residuals:
     Min       1Q   Median       3Q      Max
-1829.23  -468.73   -22.35   410.40  2150.77

Coefficients:
                 Estimate Std. Error t value Pr(>|t|)
(Intercept)       6685.76     125.33   53.35   <2e-16 ***
Процент.жирности  -684.26      28.68  -23.86   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 680.4 on 718 degrees of freedom
Multiple R-squared:  0.4422,	Adjusted R-squared:  0.4414
F-statistic: 569.3 on 1 and 718 DF,  p-value: < 2.2e-16

In [ ]:
fit <- lm(Годовой.удой.в.кг ~ Живая.масса, data = df)
summary(fit)

Call:
lm(formula = Годовой.удой.в.кг ~ Живая.масса,
    data = df)

Residuals:
    Min      1Q  Median      3Q     Max
-701.17 -200.15  -14.09  198.44  570.95

Coefficients:
              Estimate Std. Error t value Pr(>|t|)
(Intercept) -453.99849   49.51953  -9.168   <2e-16 ***
Живая.масса    8.09748    0.09325  86.837   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 268.6 on 718 degrees of freedom
Multiple R-squared:  0.9131,	Adjusted R-squared:  0.9129
F-statistic:  7541 on 1 and 718 DF,  p-value: < 2.2e-16

In [ ]:
fit <- lm(Годовой.удой.в.кг ~ Способ.кормления, data = df)
summary(fit)

Call:
lm(formula = Годовой.удой.в.кг ~ Способ.кормления,
    data = df)

Residuals:
     Min       1Q   Median       3Q      Max
-2412.93  -527.92   -12.86   573.00  2356.68

Coefficients:
                                    Estimate Std. Error t value Pr(>|t|)
(Intercept)                          4009.65      57.41  69.848  < 2e-16 ***
Способ.кормленияТравянисто-силосной  -267.91      81.18  -3.300  0.00101 **
Способ.кормленияТравяной             -489.01      81.18  -6.024 2.73e-09 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 889.3 on 717 degrees of freedom
Multiple R-squared:  0.04831,	Adjusted R-squared:  0.04565
F-statistic:  18.2 on 2 and 717 DF,  p-value: 1.955e-08

In [ ]:
fit <- lm(Годовой.удой.в.кг ~ Живая.масса + Процент.жирности + Способ.кормления, data = df)
summary(fit)

Call:
lm(formula = Годовой.удой.в.кг ~ Живая.масса +
    Процент.жирности + Способ.кормления,
    data = df)

Residuals:
    Min      1Q  Median      3Q     Max
-404.00  -78.92    2.58   73.39  371.75

Coefficients:
                                      Estimate Std. Error t value Pr(>|t|)
(Intercept)                          813.84745   42.86936   18.98   <2e-16 ***
Живая.масса                            7.42003    0.04588  161.71   <2e-16 ***
Процент.жирности                    -150.07553    5.57025  -26.94   <2e-16 ***
Способ.кормленияТравянисто-силосной -286.12170    9.74357  -29.36   <2e-16 ***
Способ.кормленияТравяной            -533.61903    9.74965  -54.73   <2e-16 ***
---
Signif. codes:  0 ‘***’ 0.001 ‘**’ 0.01 ‘*’ 0.05 ‘.’ 0.1 ‘ ’ 1

Residual standard error: 106.7 on 715 degrees of freedom
Multiple R-squared:  0.9863,	Adjusted R-squared:  0.9863
F-statistic: 1.29e+04 on 4 and 715 DF,  p-value: < 2.2e-16